/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ssliao.logging;

public class Log {
	
	private static Log INSTANCE;
	
    private Log() {
    }
    
    public static Log getInstance() {
    	if (INSTANCE == null) {
    		INSTANCE = new Log();
    	}
		return INSTANCE;
    }
}
