/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ssliao.logging;

import org.junit.Test;
import static org.junit.Assert.*;

public class LogTest {
	
    @Test public void testIsSingleton() {
        Log log = Log.getInstance();
        Log log2 = Log.getInstance();
        assertTrue(log==log2);
    }
    
}
