/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ssliao.logging;

import org.junit.Test;

import ssliao.logging.builder.ColourMessageBuilder;
import ssliao.logging.builder.DefaultMessageBuilder;
import ssliao.logging.director.BuildersDirector;
import ssliao.logging.logstream.FileStream;
import ssliao.logging.message.DefaultMessage;
import ssliao.logging.message.ErrorMessage;
import ssliao.logging.util.MessageType;

import static org.junit.Assert.*;

public class LogTest {
	
    @Test public void testIsSingleton() {
        Log log = Log.getInstance();
        Log log2 = Log.getInstance();
        assertTrue(log==log2);
    }
	
    @Test public void testIsAbstractFactoryFileStream() {
        Log log = Log.getInstance("file");
        assertTrue(log.stream instanceof FileStream);
        log = Log.getInstance("console");
        assertTrue(log.stream instanceof FileStream);
    }
	
    @Test public void testIsBuilderConstructingInfotMessageProperly() {
    	BuildersDirector director = new BuildersDirector();
    	DefaultMessageBuilder  builder = new DefaultMessageBuilder();
    	director.constructInfoMessage(builder);
    	DefaultMessage message = builder.getMessage();
    	assertEquals(message.getType(), MessageType.INFO);
    }
	
    @Test public void testIsBuilderConstructingDebugMessageProperly() {
    	BuildersDirector director = new BuildersDirector();
    	ColourMessageBuilder  builder = new ColourMessageBuilder();
    	director.constructDebugMessage(builder);
    	ErrorMessage message = builder.getErrorMessage();
    	assertEquals(message.getType(), MessageType.DEBUG);
    }
	
    @Test public void testIsBuilderConstructingErrorMessageProperly() {
    	BuildersDirector director = new BuildersDirector();
    	ColourMessageBuilder  builder = new ColourMessageBuilder();
    	director.constructErrorMessage(builder);
    	ErrorMessage message = builder.getErrorMessage();
    	assertEquals(message.getType(), MessageType.ERROR);
    }
    
}
